# Generated by Django 5.0.6 on 2024-06-19 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Additional_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field_Name', models.CharField(max_length=100)),
                ('Data', models.TextField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.employee')),
            ],
        ),
    ]
