# Generated by Django 5.0.6 on 2024-06-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_employee_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional_Details',
            new_name='Employee_Details',
        ),
    ]
