# Generated by Django 5.0.6 on 2024-06-22 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_rename_additional_details_employee_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field_Name', models.CharField(max_length=225)),
                ('Field_Type', models.CharField(choices=[('TEXT', 'TEXT'), ('NUMBER', 'NUMBER'), ('LTEXT', 'LTEXT'), ('SELECT', 'SELECT'), ('RADIO', 'RADIO')], max_length=20)),
                ('Added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee_details',
            name='Field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.field'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=225)),
                ('Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.field')),
            ],
        ),
    ]
