# Generated by Django 5.0.6 on 2024-06-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_field_employee_details_field_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='Field_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
