# Generated by Django 5.0.6 on 2024-06-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_employee_details_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='Field_Name',
        ),
    ]
