# Generated by Django 5.0.6 on 2024-06-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_remove_employee_details_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='Data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='Field_Type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('lgtext', 'lgtext'), ('select', 'select'), ('radio', 'radio')], max_length=20),
        ),
    ]
