# Generated by Django 5.0.6 on 2024-06-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_employee_details_data_alter_field_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='Field_Type',
            field=models.CharField(max_length=20),
        ),
    ]
