# Generated by Django 5.0.6 on 2024-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_field_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Mobile',
            field=models.CharField(max_length=20),
        ),
    ]
